# Hi!

# This file customizes a web page template with your info.
# Type in the appropriate info items below

# Lines of text that begin with # are COMMENTS.

# Comments are ignored by the software that feeds your info below
# into the web page template.

# This file is a derived from the HSHSL workshop Using GitHub to Manage Your Scholarly Work.

name: Kimberly Yang
email: kyang@hshsl.umaryland.edu
job_title: Research, Education and Outreach Librarian | School of Pharmacy Librarian
degrees: [JD, MLS] # type your degrees inside the square brackets in quotes and separated by a comma, ie: ["BA","MS","Ph.D"]
institution_name: University of Maryland, Baltimore
institution_URL: http://umaryland.edu
department_name: Health Sciences and Human Services Library
department_URL: http://www.hshsl.umaryland.edu

job_title: Affiliate Assistant Professor 
institution_name: University of Maryland School of Pharmacy
institution_URL: http://pharmacy.umaryland.edu
department_name: Pharmaceutical Health Services Research (PHSR) Dept
department_URL: https://www.pharmacy.umaryland.edu/about/depts/phsr/

options:
  have_selfie: false
  have_twitter: true
  have_linkedin: true

github_username: Kimberly-Yang
twitter_username: @yangkimb
linkedin_URL: https://www.linkedin.com/in/kimberlyfyang
selfie_URL: https://pbs.twimg.com/profile_images/378800000739820478/000b0ae527da8ce66fa6a0d937e7965f_400x400.jpeg

# Technical configuration
markdown: kramdown
permalinks: pretty
