# Hi!

# This file customizes a web page template with your info.
# Type in the appropriate info items below

# Lines of text that begin with # are COMMENTS.

# Comments are ignored by the software that feeds your info below
# into the web page template.

# This file is a part of the HSHSL workshop Using GitHub to Manage Your Scholarly Work.

name: 
email: 
job_title: 
degrees: [] # type your degrees inside the square brackets in quotes and separated by a comma, ie: ["BA","MS","Ph.D"]
institution_name: University of Maryland, Baltimore
institution_URL: http://umaryland.edu
department_name: 
department_URL: 

options:
  have_selfie: false
  have_twitter: false
  have_linkedin: true

github_username: 
twitter_username: 
linkedin_URL: 
selfie_URL: 

# Technical configuration
markdown: kramdown
permalinks: pretty
