# Hi!

# This file customizes a web page template with your info.
# Type in the appropriate info items below

# Lines of text that begin with # are COMMENTS.

# Comments are ignored by the software that feeds your info below
# into the web page template.

# This file is a part of the HSHSL workshop Using GitHub to Manage Your Scholarly Work.

name: Kimberly Yang
email: kyang@hshsl.umaryland.edu
job_title: Research, Education and Outreach Librarian
degrees: [JD, MLS] # type your degrees inside the square brackets in quotes and separated by a comma, ie: ["BA","MS","Ph.D"]
institution_name: University of Maryland, Baltimore
institution_URL: http://umaryland.edu
department_name: Health Sciences and Human Services Library
department_URL: http://www.hshsl.umaryland.edu

options:
  have_selfie: true
  have_twitter: true
  have_linkedin: true

github_username: Kimberly-Yang
twitter_username: yangkimb
linkedin_URL: https://www.linkedin.com/in/kimberlyfyang
selfie_URL: http://www.hshsl.umaryland.edu/CFFileServlet/_cf_image/_cfimg-9188864694515941002.PNG

# Technical configuration
markdown: kramdown
permalinks: pretty
