# Hi!

# This file customizes a web page template with your info.
# Type in the appropriate info items below

# Lines of text that begin with # are COMMENTS.

# Comments are ignored by the software that feeds your info below
# into the web page template.

# This file is a derived from the HSHSL workshop Using GitHub to Manage Your Scholarly Work.

name: Kimberly Yang
email: kyang@healthinfopro.net
degrees: [JD, MLS] # type your degrees inside the square brackets in quotes and separated by a comma, ie: ["BA","MS","Ph.D"]

job_title: Affiliate Assistant Professor
jobtitle_URL: https://www.pharmacy.umaryland.edu/about/depts/phsr/faculty/affiliate.html
institution_name: University of Maryland School of Pharmacy
institution_URL: http://pharmacy.umaryland.edu
department_name: Pharmaceutical Health Services Research (PHSR) Dept
department_URL: https://www.pharmacy.umaryland.edu/about/depts/phsr/

options:
  have_selfie: true
  have_twitter: true
  have_linkedin: true

github_username: Kimberly-Yang
twitter_username: "@yangkimb"
linkedin_URL: https://www.linkedin.com/in/kimberlyfyang
selfie_URL: https://raw.githubusercontent.com/Kimberly-Yang/kimberly-yang.github.io/master/Yang_profilepic-300_nocredit.jpg
# Technical configuration
markdown: kramdown
permalinks: pretty
